#!/usr/bin/env bash

cg_write_env_file() {
  local path="$1"
  shift

  {
    echo "# Generated by CodeGauge install-macos.sh"
    echo "# Edit values here, then run: codegaugectl restart"
    for assignment in "$@"; do
      local key="${assignment%%=*}"
      local value="${assignment#*=}"
      printf 'export %s=%q\n' "$key" "$value"
    done
  } >"$path"
}

cg_write_runner() {
  local path="$1"
  local env_file="$2"
  local binary_path="$3"

  {
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    printf 'source %q\n' "$env_file"
    printf 'exec %q\n' "$binary_path"
  } >"$path"
  chmod 0755 "$path"
}

cg_write_launchd_plist() {
  local path="$1"
  local label="$2"
  local runner_path="$3"
  local working_directory="$4"
  local stdout_path="$5"
  local stderr_path="$6"

  cat >"$path" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$(cg_xml_escape "$label")</string>
  <key>ProgramArguments</key>
  <array>
    <string>$(cg_xml_escape "$runner_path")</string>
  </array>
  <key>WorkingDirectory</key>
  <string>$(cg_xml_escape "$working_directory")</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$(cg_xml_escape "$stdout_path")</string>
  <key>StandardErrorPath</key>
  <string>$(cg_xml_escape "$stderr_path")</string>
</dict>
</plist>
PLIST
}

cg_xml_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  value="${value//\"/&quot;}"
  value="${value//\'/&apos;}"
  printf '%s' "$value"
}

cg_resolve_command() {
  local configured="$1"
  local fallback="$2"

  if [[ -n "$configured" ]]; then
    printf '%s' "$configured"
    return
  fi
  if command -v "$fallback" >/dev/null 2>&1; then
    command -v "$fallback"
    return
  fi
  printf '%s' "$fallback"
}
